services:
  telemetry-ingest:
    build: .
    ports:
      - "8000:8000"
    environment:
      - UVICORN_WORKERS=1
    command: ["uvicorn", "src.scaffold.main:app", "--host", "0.0.0.0", "--port", "8000"]
